package webservice.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-18T23:49:24.627+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "PostComment", 
                  wsdlLocation = "file:/Users/patrickgrutsch/Dropbox/Masterstudium/2.Semester/WMPM/tuwien_ss14_workflow_10/CXF_SOAP_WS/src/main/resources/wsdl/PostComment.wsdl",
                  targetNamespace = "http://www.tvgrabber.at/soap") 
public class PostComment_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.tvgrabber.at/soap", "PostComment");
    public final static QName TVGrabberSOAP = new QName("http://www.tvgrabber.at/soap", "TVGrabberSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/patrickgrutsch/Dropbox/Masterstudium/2.Semester/WMPM/tuwien_ss14_workflow_10/CXF_SOAP_WS/src/main/resources/wsdl/PostComment.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PostComment_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/patrickgrutsch/Dropbox/Masterstudium/2.Semester/WMPM/tuwien_ss14_workflow_10/CXF_SOAP_WS/src/main/resources/wsdl/PostComment.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PostComment_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PostComment_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostComment_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PostComment_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PostComment_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PostComment_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PostComment
     */
    @WebEndpoint(name = "TVGrabberSOAP")
    public PostComment getTVGrabberSOAP() {
        return super.getPort(TVGrabberSOAP, PostComment.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostComment
     */
    @WebEndpoint(name = "TVGrabberSOAP")
    public PostComment getTVGrabberSOAP(WebServiceFeature... features) {
        return super.getPort(TVGrabberSOAP, PostComment.class, features);
    }

}
