DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS TVPROGRAM;
DROP TABLE IF EXISTS TVUSER;

CREATE TABLE TVPROGRAM (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(200) NOT NULL,
description CLOB NOT NULL,
startTime TIMESTAMP NOT NULL,
endTime TIMESTAMP NOT NULL,
channel VARCHAR(200) NOT NULL,
imdbRating DECIMAL(3) DEFAULT 0
);

CREATE TABLE COMMENT (
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(200) NOT NULL,
comment CLOB NOT NULL,
tvProgram_id INTEGER NOT NULL,
CONSTRAINT fk_tvprogram_id FOREIGN KEY (tvProgram_id) REFERENCES TVProgram (id)
);

CREATE TABLE TVUSER (
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(200) NOT NULL,
subscribed BOOLEAN NOT NULL,
searchTerm VARCHAR(200) NOT NULL
);