DROP TABLE TVUser;
DROP TABLE Comment;
DROP TABLE TVProgram;

CREATE TABLE TVProgram (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  title VARCHAR(200) NOT NULL,
  description LONG VARCHAR NOT NULL,
  startTime TIMESTAMP NOT NULL,
  endTime TIMESTAMP NOT NULL,
  channel VARCHAR(200) NOT NULL
);

CREATE TABLE Comment (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  email VARCHAR(200) NOT NULL,
  comment VARCHAR(200) NOT NULL,
  tvProgram INTEGER NOT NULL,
  CONSTRAINT fk_tvprogram_id FOREIGN KEY (id) REFERENCES TVProgram (id)
);

CREATE INDEX idx_comment__tvprogram ON Comment (tvProgram);

CREATE TABLE TVUser (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  email VARCHAR(200) NOT NULL,
  subscribed INTEGER NOT NULL,
  searchTerm VARCHAR(200) NOT NULL
)