DROP TABLE IF EXISTS TVGRABBER.Comment;
DROP TABLE IF EXISTS TVGRABBER.TVProgram;
DROP TABLE IF EXISTS TVGRABBER.TVUser;

CREATE TABLE IF NOT EXISTS TVGRABBER.TVProgram (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(200) NOT NULL,
description CLOB NOT NULL,
startTime TIMESTAMP NOT NULL,
endTime TIMESTAMP NOT NULL,
channel VARCHAR(200) NOT NULL,
imdbRating DECIMAL(3) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TVGRABBER.Comment (
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(200) NOT NULL,
comment CLOB NOT NULL,
tvProgram_id INTEGER NOT NULL,
CONSTRAINT fk_tvprogram_id FOREIGN KEY (tvProgram_id) REFERENCES TVGRABBER.TVProgram (id)
);

CREATE TABLE IF NOT EXISTS TVGRABBER.TVUser (
id INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(200) NOT NULL,
subscribed BOOLEAN NOT NULL,
searchTerm VARCHAR(200) NOT NULL
);