DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS TVProgram;
DROP TABLE IF EXISTS TVUser;

CREATE TABLE IF NOT EXISTS TVProgram (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  description CLOB NOT NULL,
  startTime TIMESTAMP NOT NULL,
  endTime TIMESTAMP NOT NULL,
  channel VARCHAR(200) NOT NULL,
  imdbRating DECIMAL(3) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Comment (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(200) NOT NULL,
  comment CLOB NOT NULL,
  tvProgram_id INTEGER NOT NULL,
  CONSTRAINT fk_tvprogram_id FOREIGN KEY (tvProgram_id) REFERENCES TVProgram (id)
);

CREATE TABLE IF NOT EXISTS TVUser (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(200) NOT NULL,
  subscribed BOOLEAN NOT NULL,
  searchTerm VARCHAR(200) NOT NULL
);